name: 'Coverage'
on:
  pull_request_target:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: npm install
        run: npm install

      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          output: report-markdown
          skip-step: install
          test-script: npm run test:coverage
          package-manager: npm

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}
